spring.application.name=backoffice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.session.timeout=24h
server.servlet.session.cookie.http-only=true
spring.profiles.active=local